twitter:
  consumer_key: consumer_key_value
  consumer_secret: consumer_secret_value
  access_token: access_token_value
  access_token_secret: access_token_secret_value

redis:
  host_name: localhost
  port: 6379
  password: dummy

other:
  key: value
